### ISSUE TITLE
Message.toString() is problematic with repeating groups

### ISSUE THREAD

**Issue by robertbetts** [akhin/tinyFIX#1]
https://github.com/akhin/tinyFIX/blob/8e13d0c3f7a4077946279bda5bc9db932bba6e61/library_package/tinyFix/FixMessage.py#L172

I have altered this line to include the tag value: 
`appendToMessageAsString(tag, value)`

The only way I have been able to get repeating tags appended to the message is by way of :
`.setTags(list_of_tag_value_tuples)`. 
setTag (no index) and appendTag, both overwrite the the first occurrence.

In the context of this issue, the example,  tinyFIX/examples/example_fix_client.py works for creating an order with the repeating group NoPartyIDs.  However on the receiving end, the values for the received groups are all the same as that of the first party group.

**Comment by akhin** [comment]
Thanks a lot for spotting it. Have applied your suggestion for body building part. Also fixed FixMessage::setTag when using with index and update setTags so it always appends

Repeating groups will be transmitted properly now in server-client examples

Also when building a fix message with repeating group , alternative ways : 

```
order = FixMessage()
order.setTag(453, 3)
order.setTag(448 ,1234)
order.setTag(447, 'P')
order.setTag(452, 1)
order.setTag(448 ,1235, 2)
order.setTag(447, 'R', 2)
order.setTag(452, 2, 2)
order.appendTag(448, 1236)
order.appendTag(447, 'c')
order.appendTag(452 ,3)

# for getting value
test = order.getTagValue(447, 3)

```

**Comment by robertbetts** [comment]
Very cool, this is exactly how I originally assumed these methods worked.
